feat : revised main-service, video-service, data.sql(dummy)
StreamingGate/Playground pull request #205
Opened 2022-02-10 10:51 UTC by kimhanui

- main-service: 좋아요 싫어요 기능 수정
- video-service: lastViewedAt 값 넣는 메서드 추가
- data.sql: 기존 더미데이터에의 비워둔 컬럼 값에 값 삽입

2022-02-10 10:51 UTC, ag502 approved these changes
LGTM 😎😎😎

2022-02-10 10:52 UTC, Chaehui-Seo approved these changes
LGTM😎😎

2022-02-11 08:22 UTC, kmswlee requested changes

2022-02-11 08:22 UTC, kmswlee commented on src/server/main-service/src/main/java/com/example/mainservice/entity/RoomViewer/RoomViewer.java
> +        if (this.disliked == false && disliked == true) {
혹시 if(this.disliked == false && disliked == true && this.liked == true) 묶어도 되지 않을까요?

2022-02-11 09:09 UTC, kmswlee approved these changes
LGTM !

2022-02-11 09:14 UTC, merged