design : RegisterPage UI markup
StreamingGate/Playground pull request #65
Opened 2022-01-19 12:39 UTC by ag502

Resovled #59

2022-01-19 12:40 UTC, ag502 commented
시간 나시면 아래 링크 보시고 피드백 주시면 감사하겠습니다~~~ 😂😂

2022-01-19 14:30 UTC, kmswlee approved these changes
LGTM!! 👍  🔥

2022-01-19 14:33 UTC, kimhanui requested changes
사진 업로드 -> 기본이미지로 변경 -> 다시 사진 업로드 하려니까 업로드가 안됩니다 !

2022-01-19 14:47 UTC, Chaehui-Seo reviewed
LGTM👍 몇가지 사소한 디자인 피드백 남깁니다

- 텍스트필드 디자인이 border없이 background색상으로 배경 채워주시면 좋을 것 같습니다
- 마지막 페이지에서 너비가 살짝 늘어나는게 "가입하기"글자수 때문이라면 2글자로 맞춰서 "가입"으로 변경해도 무관할 것 같습니다😉
- 프로필 사진 파일업로드하면, fit 말고 fill 모드(비율은 그래도하되 크기가 안 맞으면 잘리도록) 하면 좋을 것 같아요
- 더불어 하늬님이 말씀하신 부분에서, 같은 사진으로 A파일업로드-기본이미지로변경-A파일업로드하면 안되지만, A파일업로드-기본이미지로변경-B파일업로드 하면 잘 들어갑니다! 참고해주세요~

2022-01-19 15:20 UTC, ag502 commented
> 사진 업로드 -> 기본이미지로 변경 -> 다시 사진 업로드 하려니까 업로드가 안됩니다 !

리뷰 감사합니다~~ 확인 후 수정하겠습니다 .🙇‍♂️🙇‍♂️

2022-01-19 15:20 UTC, ag502 commented
> LGTM👍 몇가지 사소한 디자인 피드백 남깁니다
> 
> * 텍스트필드 디자인이 border없이 background색상으로 배경 채워주시면 좋을 것 같습니다
> * 마지막 페이지에서 너비가 살짝 늘어나는게 "가입하기"글자수 때문이라면 2글자로 맞춰서 "가입"으로 변경해도 무관할 것 같습니다😉
> * 프로필 사진 파일업로드하면, fit 말고 fill 모드(비율은 그래도하되 크기가 안 맞으면 잘리도록) 하면 좋을 것 같아요
> * 더불어 하늬님이 말씀하신 부분에서, 같은 사진으로 A파일업로드-기본이미지로변경-A파일업로드하면 안되지만, A파일업로드-기본이미지로변경-B파일업로드 하면 잘 들어갑니다! 참고해주세요~

늦은시간에 리뷰 남겨주셔서 감사합니다~~ 🙇‍♂️

2022-01-20 02:58 UTC, ag502 commented
어제 말씀하신 피드백 반영했습니다.

https://61d257a71897c4003a50a451-yuejevnjdx.chromatic.com/?path=/story/page-register--register

시간나실때 확인해 보시고 피드백 주시면 감사하겠습니다~~

2022-01-20 02:59 UTC, Chaehui-Seo approved these changes
LGTM!😁

2022-01-20 04:18 UTC, kimhanui approved these changes
아주 잘 됩니다~ LGTM 👍

2022-01-20 04:19 UTC, merged